# Generated by Django 4.2.30 on 2026-05-24 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++')], max_length=10)),
                ('code', models.TextField()),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='safe', max_length=10)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('bug_type', models.CharField(choices=[('syntax', 'Syntax Error'), ('logical', 'Logical Error'), ('runtime', 'Runtime Error'), ('warning', 'Warning'), ('style', 'Style Issue')], max_length=20)),
                ('description', models.TextField()),
                ('fix_suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='core.codesession')),
            ],
        ),
    ]
