# Generated by Django 4.2.30 on 2026-05-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.bugreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
